[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs."http://127.0.0.1:8899"]
list = "5C6FGUgM3o2gULHhcRu1TnoHcKLVvezxZZThZTJiwqrM"

[programs.localnet]
anchor_program = "5C6FGUgM3o2gULHhcRu1TnoHcKLVvezxZZThZTJiwqrM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
